---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# See https://prek.j178.dev to learn about prek

# exclude: ""

# pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=2000, --enforce-all]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

      - id: check-docstring-first
      - id: name-tests-test

  # actionlint
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint

  # zizmor
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815 # frozen: v1.26.1
    hooks:
      - id: zizmor

  # yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: [--config-file=.github/linters/.yamllint.yml, --strict]

  # betterleaks
  - repo: https://github.com/betterleaks/betterleaks
    rev: 6475f3fe49bf893d7713cd501131176a051f8d10 # frozen: v1.6.0
    hooks:
      - id: betterleaks

  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell

  - repo: local
    hooks:
      # ruff
      - id: ruff-check
        name: ruff check
        entry: uv run --locked ruff check --fix
        language: system
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: uv run --locked ruff format
        language: system
        types: [python]
        require_serial: true

      # ty
      - id: ty
        name: ty check
        entry: uv run --locked ty check
        language: system
        pass_filenames: false
        always_run: true
        require_serial: true
