---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - PYTHON
  - SPELL
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD

FLAVOR_SUGGESTIONS: false
GITHUB_COMMENT_REPORTER: true
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (^\.github/PULL_REQUEST_TEMPLATE\.md$)
YAML_YAMLLINT_ARGUMENTS: --strict
