---
# Documentation:
#   - https://code.visualstudio.com/docs/devcontainers/create-dev-container#_use-docker-compose
#   - https://stackoverflow.com/questions/69635634/how-to-use-vs-code-dev-container-with-existing-docker-compose-file
#   - https://xebia.com/blog/how-to-create-a-devcontainer-for-your-python-project/

services:
  ppt-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: ppt-devcontainer
    tty: true
    volumes:
      - ../:/workspace
